name: Test and linter

on:
  #pull_request:
  #workflow_dispatch:
  push:
    branches:
    - cairo1-ci
    #- cairo-1

env:
  CARGO_TERM_COLOR: always

jobs:
  lint_and_test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Lint Code Base
      uses: DavidAnson/markdownlint-cli2-action@v9
      with:
        globs: '*.md, !PULL_REQUEST_TEMPLATE'

    - name: Cairo linter
      run: make check-format
    - name: Cairo test
      run: make test


#    - name: Markdown lint
#      uses: docker://avtodev/markdown-lint:v1
#      with:
#        args: '*.md'
#        ignore: './PULL_REQUEST_TEMPLATE.md'